import Link from "next/link";
import React from "react";

export const metadata = {
  title: "GET api",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return (
    <>
      <nav>
        <h3>Selecion provincia</h3>
        <nav>
          <ul>
            <li>
              <Link href='/clima/categoria/santiago'>Santiago</Link>
            </li>
            <li>
              <Link href='/clima/categoria/moca'>Moca</Link>
            </li>
          </ul>
        </nav>
      </nav>
      {children}
    </>
  );
};

export default layout;
